"""add teams matches veto maps; drop tracked teams

Revision ID: 2e4d9a5d721a
Revises: 6fde9624e75f
Create Date: 2026-02-02 19:10:55.429644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e4d9a5d721a'
down_revision: Union[str, Sequence[str], None] = '6fde9624e75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_maps', sa.Column('team1_rounds', sa.Integer(), nullable=True))
    op.add_column('match_maps', sa.Column('team2_rounds', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_match_maps_team1_id'), table_name='match_maps')
    op.drop_index(op.f('ix_match_maps_team2_id'), table_name='match_maps')
    op.drop_constraint(op.f('match_maps_team2_id_fkey'), 'match_maps', type_='foreignkey')
    op.drop_constraint(op.f('match_maps_team1_id_fkey'), 'match_maps', type_='foreignkey')
    op.drop_column('match_maps', 'team1_id')
    op.drop_column('match_maps', 'team2_id')
    op.add_column('matches', sa.Column('url', sa.String(length=512), nullable=True))
    op.add_column('matches', sa.Column('team1_id', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('team2_id', sa.Integer(), nullable=False))
    op.alter_column(
            "matches",
            "played_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            type_=sa.Integer(),
            nullable=False,
            postgresql_using="EXTRACT(EPOCH FROM played_at)::integer",
        )
    op.create_index(op.f('ix_matches_team1_id'), 'matches', ['team1_id'], unique=False)
    op.create_index(op.f('ix_matches_team2_id'), 'matches', ['team2_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_team2_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_team1_id'), table_name='matches')
    op.alter_column('matches', 'played_at',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('matches', 'team2_id')
    op.drop_column('matches', 'team1_id')
    op.drop_column('matches', 'url')
    op.add_column('match_maps', sa.Column('team2_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_maps', sa.Column('team1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('match_maps_team1_id_fkey'), 'match_maps', 'teams', ['team1_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('match_maps_team2_id_fkey'), 'match_maps', 'teams', ['team2_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_match_maps_team2_id'), 'match_maps', ['team2_id'], unique=False)
    op.create_index(op.f('ix_match_maps_team1_id'), 'match_maps', ['team1_id'], unique=False)
    op.drop_column('match_maps', 'team2_rounds')
    op.drop_column('match_maps', 'team1_rounds')
    # ### end Alembic commands ###
