"""add teams matches veto maps; drop tracked teams

Revision ID: 6fde9624e75f
Revises: 6d4d86f63807
Create Date: 2026-02-02 18:38:42.552491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fde9624e75f'
down_revision: Union[str, Sequence[str], None] = '6d4d86f63807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_played_at'), 'matches', ['played_at'], unique=False)
    op.create_index(op.f('ix_matches_source'), 'matches', ['source'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('grid_team_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_grid_team_id'), 'teams', ['grid_team_id'], unique=True)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('match_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(length=32), nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_maps_map_name'), 'match_maps', ['map_name'], unique=False)
    op.create_index(op.f('ix_match_maps_match_id'), 'match_maps', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_maps_team1_id'), 'match_maps', ['team1_id'], unique=False)
    op.create_index(op.f('ix_match_maps_team2_id'), 'match_maps', ['team2_id'], unique=False)
    op.create_index(op.f('ix_match_maps_winner_team_id'), 'match_maps', ['winner_team_id'], unique=False)
    op.create_table('match_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_match_team')
    )
    op.create_index(op.f('ix_match_teams_match_id'), 'match_teams', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_teams_team_id'), 'match_teams', ['team_id'], unique=False)
    op.create_table('veto_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('map_name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'order_index', name='uq_veto_order')
    )
    op.create_index(op.f('ix_veto_actions_action'), 'veto_actions', ['action'], unique=False)
    op.create_index(op.f('ix_veto_actions_map_name'), 'veto_actions', ['map_name'], unique=False)
    op.create_index(op.f('ix_veto_actions_match_id'), 'veto_actions', ['match_id'], unique=False)
    op.create_index(op.f('ix_veto_actions_order_index'), 'veto_actions', ['order_index'], unique=False)
    op.create_index(op.f('ix_veto_actions_team_id'), 'veto_actions', ['team_id'], unique=False)
    op.drop_index(op.f('ix_tracked_teams_grid_team_id'), table_name='tracked_teams')
    op.drop_index(op.f('ix_tracked_teams_is_active'), table_name='tracked_teams')
    op.drop_index(op.f('ix_tracked_teams_name'), table_name='tracked_teams')
    op.drop_table('tracked_teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_teams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('grid_team_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tracked_teams_pkey'))
    )
    op.create_index(op.f('ix_tracked_teams_name'), 'tracked_teams', ['name'], unique=True)
    op.create_index(op.f('ix_tracked_teams_is_active'), 'tracked_teams', ['is_active'], unique=False)
    op.create_index(op.f('ix_tracked_teams_grid_team_id'), 'tracked_teams', ['grid_team_id'], unique=True)
    op.drop_index(op.f('ix_veto_actions_team_id'), table_name='veto_actions')
    op.drop_index(op.f('ix_veto_actions_order_index'), table_name='veto_actions')
    op.drop_index(op.f('ix_veto_actions_match_id'), table_name='veto_actions')
    op.drop_index(op.f('ix_veto_actions_map_name'), table_name='veto_actions')
    op.drop_index(op.f('ix_veto_actions_action'), table_name='veto_actions')
    op.drop_table('veto_actions')
    op.drop_index(op.f('ix_match_teams_team_id'), table_name='match_teams')
    op.drop_index(op.f('ix_match_teams_match_id'), table_name='match_teams')
    op.drop_table('match_teams')
    op.drop_index(op.f('ix_match_maps_winner_team_id'), table_name='match_maps')
    op.drop_index(op.f('ix_match_maps_team2_id'), table_name='match_maps')
    op.drop_index(op.f('ix_match_maps_team1_id'), table_name='match_maps')
    op.drop_index(op.f('ix_match_maps_match_id'), table_name='match_maps')
    op.drop_index(op.f('ix_match_maps_map_name'), table_name='match_maps')
    op.drop_table('match_maps')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_grid_team_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_matches_source'), table_name='matches')
    op.drop_index(op.f('ix_matches_played_at'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
