"""add match flags event_id series_id

Revision ID: 8f4224243633
Revises: 2e4d9a5d721a
Create Date: 2026-02-05 14:29:26.645043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4224243633'
down_revision: Union[str, Sequence[str], None] = '2e4d9a5d721a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_teams_match_id'), table_name='match_teams')
    op.drop_index(op.f('ix_match_teams_team_id'), table_name='match_teams')
    op.drop_table('match_teams')
    op.add_column('matches', sa.Column('event_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('series_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('is_seeding_match', sa.Boolean(), nullable=False))
    op.add_column('matches', sa.Column('is_third_place_decider', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_matches_event_id'), 'matches', ['event_id'], unique=False)
    op.create_index(op.f('ix_matches_series_id'), 'matches', ['series_id'], unique=False)
    op.add_column('players', sa.Column('name', sa.String(length=128), nullable=False))
    op.drop_index(op.f('ix_players_handle'), table_name='players')
    op.create_unique_constraint('uq_players_name', 'players', ['name'])
    op.drop_column('players', 'handle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('handle', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint('uq_players_name', 'players', type_='unique')
    op.create_index(op.f('ix_players_handle'), 'players', ['handle'], unique=True)
    op.drop_column('players', 'name')
    op.drop_index(op.f('ix_matches_series_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_event_id'), table_name='matches')
    op.drop_column('matches', 'is_third_place_decider')
    op.drop_column('matches', 'is_seeding_match')
    op.drop_column('matches', 'series_id')
    op.drop_column('matches', 'event_id')
    op.create_table('match_teams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('match_teams_match_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('match_teams_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('match_teams_pkey')),
    sa.UniqueConstraint('match_id', 'team_id', name=op.f('uq_match_team'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_match_teams_team_id'), 'match_teams', ['team_id'], unique=False)
    op.create_index(op.f('ix_match_teams_match_id'), 'match_teams', ['match_id'], unique=False)
    # ### end Alembic commands ###
