"""add tracked teams

Revision ID: 9e0760e3e733
Revises: 38d8f0e68059
Create Date: 2026-01-30 21:36:22.105858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0760e3e733'
down_revision: Union[str, Sequence[str], None] = '38d8f0e68059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('grid_team_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_teams_grid_team_id'), 'tracked_teams', ['grid_team_id'], unique=True)
    op.create_index(op.f('ix_tracked_teams_is_active'), 'tracked_teams', ['is_active'], unique=False)
    op.create_index(op.f('ix_tracked_teams_name'), 'tracked_teams', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_teams_name'), table_name='tracked_teams')
    op.drop_index(op.f('ix_tracked_teams_is_active'), table_name='tracked_teams')
    op.drop_index(op.f('ix_tracked_teams_grid_team_id'), table_name='tracked_teams')
    op.drop_table('tracked_teams')
    # ### end Alembic commands ###
