"""add stats table

Revision ID: c8df43a37a95
Revises: 8f4224243633
Create Date: 2026-02-05 21:36:21.171905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8df43a37a95'
down_revision: Union[str, Sequence[str], None] = '8f4224243633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_map_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('stats_match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(length=32), nullable=True),
    sa.Column('segment', sa.String(length=8), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('hs_kills', sa.Integer(), nullable=True),
    sa.Column('adr', sa.Float(), nullable=True),
    sa.Column('kast', sa.Float(), nullable=True),
    sa.Column('rating3', sa.Float(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stats_match_id', 'player_id', 'segment', name='uq_player_map_stats_row')
    )
    op.create_index(op.f('ix_player_map_stats_map_name'), 'player_map_stats', ['map_name'], unique=False)
    op.create_index(op.f('ix_player_map_stats_match_id'), 'player_map_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_map_stats_player_id'), 'player_map_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_map_stats_segment'), 'player_map_stats', ['segment'], unique=False)
    op.create_index(op.f('ix_player_map_stats_stats_match_id'), 'player_map_stats', ['stats_match_id'], unique=False)
    op.create_index(op.f('ix_player_map_stats_team_id'), 'player_map_stats', ['team_id'], unique=False)
    op.add_column('matches', sa.Column('stats_match_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('stats_match_slug', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_matches_stats_match_id'), 'matches', ['stats_match_id'], unique=False)
    op.drop_constraint(op.f('uq_players_name'), 'players', type_='unique')
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.create_unique_constraint(op.f('uq_players_name'), 'players', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_matches_stats_match_id'), table_name='matches')
    op.drop_column('matches', 'stats_match_slug')
    op.drop_column('matches', 'stats_match_id')
    op.drop_index(op.f('ix_player_map_stats_team_id'), table_name='player_map_stats')
    op.drop_index(op.f('ix_player_map_stats_stats_match_id'), table_name='player_map_stats')
    op.drop_index(op.f('ix_player_map_stats_segment'), table_name='player_map_stats')
    op.drop_index(op.f('ix_player_map_stats_player_id'), table_name='player_map_stats')
    op.drop_index(op.f('ix_player_map_stats_match_id'), table_name='player_map_stats')
    op.drop_index(op.f('ix_player_map_stats_map_name'), table_name='player_map_stats')
    op.drop_table('player_map_stats')
    # ### end Alembic commands ###
