"""players must have unique handle names

Revision ID: ddc5518af87f
Revises: a8e0f7eebd66
Create Date: 2026-01-29 18:01:10.075029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc5518af87f'
down_revision: Union[str, Sequence[str], None] = 'a8e0f7eebd66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_handle'), table_name='players')
    op.create_index(op.f('ix_players_handle'), 'players', ['handle'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_handle'), table_name='players')
    op.create_index(op.f('ix_players_handle'), 'players', ['handle'], unique=False)
    # ### end Alembic commands ###
